import Foundation

var options = ["eventName": ["option": "nextEvent"]];
var events = ["event": "text"];
var game = true;
var alphabet = "ABCDEF";
var optionCounter = 0;
events = ["overview_4": """
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&%&&&&&&&&&&&&&&&&&&&&&&&&&&&%&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&@@@&&&&&&&&&&&&&&&&&&&&&&&@@@&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@%&&&&&&&&&&&&&&&&@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@%@@&&&&&&&&&&&@@%@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@@@@@@&&&%&@@@@@@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%@@@@@@&&%%%&&@@&@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@&@@@@@@@%@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%@&@@@&&@@&@%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%@%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                        &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

                        Jest rok 3308 i ludzkość panuje nad kosmosem. Dzięki wynalezieniu napędu FSD, paliwa wodorowego i kompputerów potężniejszych, niż kiedykolwiek wcześniej, gwiazdy znalazły się w zasięgu ręki. Poczynając od 22 wieku, ludzkość masowo zaczyna kolonizwoać kosmos. Jednak o ile na Ziemi wojna światowa dobitnie pokazała, że jedynie zjednoczona ludzkość przeżyje, odkrywcy kosmosu zapomnieli o tej lekcji. Już pierwsza ludzka kolonia poza Układem Słonecznym wkrótce po osiągnięciu samowystarczalności ogłosiła niepodległość, zmuszając władze z Ziemi do zbrojnej interwencji. I o ile obie strony doszły w końcu do ugody, tak nie zakończyło to sporów na zawsze. Ludzka chciwość doprowadziła do wytępienia wszystkich obcych form życia, najpierw na Tau Ceti, a potem w kolejnych koloniach. I o ile z czasem ludzie zaczęli przykładać większą wagę do ochrony obcych, tak cały czas nie mogą pogodzić się ze sobą. Na tym polega paradoks ludzkiego zachowania: mimo, że praktycznie nieskończony wszechświat jest na wyciągnięcie ręki, ludzie i tak walczą między sobą o najmniejszą drobnostkę, przelewając niepotrzebnie krew. Dzisiaj, kiedy zasiedlonych systemów są tysiące, a populację ludzkości liczy się w tryliardach, trzy największe mocarstwa rywalizują o wpływy w zamieszkałej przestrzeni: Imperium, Federacja i Sojusz. Mimo ich nieustannych nacisków tysiące systemów wybierają \"czwartą drogę\", będąc niezależnymi od żadnego z nich. Wybierz opcję: \nA - Informacje o Imperium \nB - informacje o Federacji \nC - informacje o Sojuszu \nD - kontynuuj fabułę
                        """,
          "overviewEmpire_1": """
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                @ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,
                                @@@/@@@@@@@ @@@@@@@@@@@@.@./&@(#. %%/%@@@@@@,(@*@ (/@@/,@%@@@@ @@.(@@@@@ %@@@#,@
                                @@@@@(@@@&&,#@@.@@@ %%,@*@@@@ @ *@@@@@@@@@@@@@@@@@%..@@@..@@@@@@@@, @@(*@@@@ @@@
                                @@@@@@%@@@@(@@&&@@@@.@ @@@ (,/@@@@@@@,@@@@@@ #@@@@@@&@@@@@@@@@@&@%/&% @@@@ @@@@@
                                @@@@@@@@@@@@@&(@@#%@@@@@@#,#@@@@@@@@@@#*@@@@@/@@#*#@@@@@@@@@@,#@@@@*@@@@.&@@@@@@
                                @@@@@@@@@@.@@@@ @@@@/%@@@@@@@@&./#@@@/(@@@@@@(*@@@@@@@@@@@%#@@@@@(&@@@*(@@@@@@@@
                                @@@@@@@@@@@.*@@@@@@@@@@/@@@@@@@@@@@@,/@@@.,@@@@@@@@@@@@@.**@@@@,(@@@( @@@@@@@@@@
                                @@@@@@@@@@@@@,%@@@@@@@*/@@ @@@@@@@@@@@@@@@@@@@@@@@@@@(#@@@@@@,,@@@@ @@@@@@@@@@@@
                                @@@@@@@@@@@@@@@/@@@@##*/@@@@@ @@@@@@@@@@@@@@@@@@@@@ @@@@@@@@*@@@@/@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@*@@@@*,/.@@@@@(,@@@@@@@@@@@@@@@*(@@@@@@,,@@@@@.@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@(.@@@@*(@@@@@@@@@.@@@@@@@@@@ @@@@@@@@ %&@@@,(@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@%/@@@@#(@@@@@@@@.@@@@@@@&/@@@@@@@(,&@@@(&@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@ @@@@@/.@@@@@@@/@@@@@#@@@@@@@,*&@@@@ @@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@ @@@@#%*@@@@@@@@@@,(@@@@@ @.@@@@.@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@.@@@@/ @*@&,/,@**.#@/  .@@@@ @@@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@ *@@@@,%@@@@@@@@@@@@&&@@@,#@@@@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@/%@@@@,@@@@@@@@@(/@@@(*@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,@@@@@.@@@@@(*@@@@%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,@@@@# @@.@@@@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,@@@@/@@@@.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(@@@@@,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,@@/%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                Imperium \n\"Kiedy nasi przodkowie opuścili Ziemię, zadali sobie pytanie: które z naszych osiągnięć reprezentuje to, co najlepsze w ludzkości, abyśmy mogli zabrać je ze sobą, aby oświetlić ciemność? Federacja, uwikłana w świat kontraktów i drobnych sprzeczek, wybrała swoją Konstytucję. Zaufali nie samemu człowiekowi, ale niedoskonałemu dziełu człowieka. Ale mój przodek – twój pierwszy cesarz – był mądrzejszy. Wiedział, że najlepszym osiągnięciem ludzkości jest sama ludzkość. W jednym nukleotydzie jego szlachetnego DNA było więcej mądrości niż we wszystkich pisanych tekstach Federacji. Ta sama mądrość wciąż nas prowadzi. Nie potrzebujemy zakurzonych dokumentów, aby dowodzić naszych praw! Jesteśmy ludźmi, urodziliśmy się by rządzić... a wszechświat czeka na silną rękę naszego rządzenia.\" Ten cytat Imperatora Traskena Duvala II bardzo dobrze podsumowuje podstawy Imperium Achenarskiego. Podczas gdy Federacja zdecydowała się kontynuować liberalne tradycje Ziemi, tak władcy Imperium postanowili rządzić za pomocą silnej ręki. Po założeniu pierwszej swojej kolonii w systemie Achenar, Imperator Henson Duval wprowadził serię praw zmieniającyh pacyfistyczną republikę w autokratyczną monarchię, z mocno ograniczoną rolą Senatu Imperium. Gdy wieści o tym dotarły do Federacji, zdecydowano się na wysłanie do ekspedycji karnej do Achenaru. Przybyła tam flota została jednak zaskoczona przez siły imperialne i zmuszona była się wycofać. Wojna podjazdowa, która trwała przez następne lata, zakończyła się ostatecznie porażką Federacji i uznaniem przez nią niezalezności Imperium. Od tego czasu stosunki między tymi dwoma mocarstwami są chłodne, a często wybuchające konflikty pochłonęły niezliczoną ilość ofiar. Społeczeństwo imeprialne oparte jest na systemie feudalnym, w którym tylko arystokracji przysługują swobody i prawa wyborcze, a praca niewolnicza wykorzystywana jest w każdym sektorze gospodarki. \nWybierz opcję: \nA - powrót
                                """,
          "overviewFederation_1": """
                                                &                                                            
                                            @@@@&&&@@&             (&@@@.                                    
                                                @@@@       @@  @@,          #@  /@                            
                                                @    @  @  &       &@,   .@@       /# @                        
                                                    @ (      @      /@@@%      ,.     @ &                     
                                        &          & &     @           *@      /   *     %  @                  
                                    &&%&&      @ @     /   &         @@.       %   (     @ .,                
                                    @  &     &  @     #             @@@@                   / @               
                                            &  @     &   @       @@@&@@@@@@,                , &              
                                            %. @          %   .@@@@@@@@@@@&%@@@.       @     %  &      &      
                                    *       @  @          @          @@@@         %    @      @ &             
                                    ,&&&      %  /      @    &         *%&@        #            &  &            
                                            #  &      .#    .@        @@        @     @       &  &      %     
                                            &  &        @     &@@           &@    @@@@@      @  ,@      &%    
                                            @   &        @@          .*,           &@@.     &@  &             
                                    &&      @   @          &@                  @@         &&  %&             
                                            @@   @@           %@@@&     %@@@@            &   %@              
                                        .@     (@    @@&@@&                             ,&&   &&   /&@&&&&     
                                                @@  @@@@@@@                          &&    (&,      &/&@      
                                                ,@@ %@@@@@@@                   .@@&     @@&                  
                                                    @@@       @@@@@@@@@@@@@@@@@,      .&&  &                  
                                                        @@@,                        &&&(   &&                  
                                                            @@@@@@@,        /@&@@@@.      %&&&*                
                                                                    (@@@@@#               &   &                
                                    Federacja \n \"Jak zatem podjąć niewykonalne zadanie podsumowania Federacji? To my wyznaczamy granice. Nasi przodkowie, którzy przeżyli gorzką udrękę globalnych wojen, wyznaczyli linię i oświadczyli: nigdy więcej. Zapisaliśmy prawa wszystkich obywateli w naszej Konstytucji, podkreśliliśmy je i podpisaliśmy. Wykreśliliśmy linie, które jako pierwsze połączyły systemy gwiezdne, sprowadzając ludzkość do wybrzeży nowych światów, otwierając drogę do międzygwiezdnego handlu. A kiedy sama ludzkość, w obfitości młodości, zagroziła delikatnej równowadze obcego życia, ponownie narysowaliśmy granicę; do tej pory kroczmy zgodnie z prawem, a nie dalej.\" To cytat z mowy inauguracyjnej Isaaca Gellana, byłego prezydenta Federacji. Powstała ze zjednoczenia państw na Ziemi, Federacja jest najstarszym państwem międzygwiezdnym. W uchwalonej po buncie kolonii ludzkiej w systemie Tau Ceti konstytucji, Federacja zobowiązuje się chronić praworządności, demorkacji i wolności obywatelskich, a także proklamuje równouprawnienie wszystkich form życia. Ten wyidealizowany dokument często przegrywa starcie z rzeczywistością, w której to ogromne międzykalaktyczne korporacje wywierają wpływ na senatorów obradujących w stolicy Federacji, na Marsie, a skandale korupcyjne regularnie pojawiają się na łamach gazet. Mimo wszystko mieszkańcy systemów wchodzących w jej skład mogą cieszyć się swobodnym życiem na wysokim z reguły poziomie, mimo czunych oczu Federalnej Agencji Bezpieczeństwa. \nWybierz opcję: \nA - powrót
                                    """,
          "overviewAlliance_1": """
                                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%&&&&&%%%&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%&&#  %&&& &&&&&# *&&&%&%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                &&&&&&&&&&&&&&&&&&&&&&&&&&&&& /&&&&&&&  &&&&&&&&&& *&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&&& &&&&&&&&&   & #&&&&&&&&&% &&&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&.&&&&&&&&&(    &   &&&&&&&&&& %&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&& %&&&&&&&&,     &     &&&&&&&&& &&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&& &&&&&&&&       &       &&&&&&&& &&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&%&&&&&&&       &&#       /&&&&&& &&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&& &&&&&&   *&@      ,&&     &&&&& &&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&,(&&&&&&%               @@,  && &&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&&&&*       ..*#&@&&&&&&&&&&&&%&&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&&& &&&&&&&&&&&&&&&&&&&&&&&&%&&&&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&&&&&( &&&&&&&&&&&&&&&&&&( &&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@/  #&&&&&&&,  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                                &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                                Sojusz \n \"Jeśli mamy doprowadzić do powstania Sojuszu Niezależnych Systemów, potrzebujemy czegoś więcej niż przemów bohaterów wojennych. Musimy pokazać ludziom, że to cholerstwo może działać. Chcę plany wydatków, prognozy dywidend, raporty geodetów. Chcę danych tak suchych, że nie musisz w nie wierzyć. Ludzie są zmęczeni i wykończeni. Obie strony zbyt wiele razy sprzedały im sny, więc nie próbujmy ich więcej sprzedawać. Czas się obudzić.\" Ta prywatna wiadomość wymieniona między Ojcami Założycielami Sojuszu, Meredithem Argentem i Miciem Turnerem, wiele mówi o podstawie, na jakiej opiera się Sojusz. Zgodnie z zasadą \"Gdzie dwóch się bije, tam wszyscy cierpią\", populacja systemu Alioth, mimo posiadania ogromnych złóż gazu i minerałów praktycznie pod ręką, żyła w biedzie. O ten system bowiem toczyły się praktycznie nieustanne walki między Federacją a Imperium. Przez wieki system ten był podzielony między te dwa mocarstwa, a populacja wyzyskiwana przez obie strony jednakowo. Wszelkie próby buntu kończyły się tragicznie, a na powstańcach stosowano surowe kary. Mieszkańcy Alioth nie tracili jednak nadziei na to że kiedyś będą żyli w świecie wolnym od obcej opresji. Gdy w 3228 federacyjna megakorporacja ogłosiła podniesienie cen żywności, mieszkańcy planety Turner's World ogłosili strajk. Próby rozbicia go siłą zarówno przez Federację, jak i Imperium spełzły na niczym, a dzięki pomocy pobliskich niepodległych systemów udało się wypędzić okręty obu walczących stron. Zarówno od niedawna niepodległy Alioth, jak i inne pobliskie systemy zdawały sobie sprawę, że prędzej czy później najeźdźcy powrócą. W 3230 r. został utworzony Sojusz Niepodległych Systemów, ostoja demokracji wśród autorytartyzmu Imperium i skrajnego kapitalizmu Federacji. Systemy Sojuszu szczycą się posiadaniem największych praw obywatelskich w zamieszkałej przestrzeni, a ich obywatele nie są wykorzystywani przez żadne korporacje, ani arystokratów. Niemniej jednak Sojusz cały czas jest najmniejszym z trzech mocarstw, a jego parlament, mimo że najbardziej demokratyczny ze wszystkich mocarstw, jest często skłócony i długo debatuje nad każdą ustawą. \nWybierz opcje: \nA - powrót
                                """,
          "introduction_2": "Jednym z niezależnych systemów jest znajdujący się na Pograniczu 'HR 8444'. Pograniczem określa się obszar na krańcu zamieszkałej przestrzeni, z dala od kolebki ludzkości. Sam 'HR 8444' znajduje się w odległości ponad 200 lat świetlnych od Układu Słonecznego. Na Pograniczu wpływy wielkich mocarstw galaktycznych są słabe, a w systemach rządzą frakcje obejmujące z reguły kilka systemów. Wiele z nich należy do Koalicji Pogranicza, paktu militarno-dyplomatycznego ułatwiającego handel i koordynującego działania zbrojne między członkami. Sama Koalicja nie ma jednak praktycznie żadnej kontroli nad sprawami wewnętrznymi swoich członków, skupiając się jedynie na obronie ich przed wpływami z zewnątrz. Oficjalna siedziba większości urzędów Koalicji znajduje się w 'HR 8444', na stacji Maskelyne Vision. I rzeczywiście, przechadzając się jej szerokimi alejami nie sposób nie dostrzec mieszanki kultur i zwyczajów, która nadaje jej atmosferę podobną do tej często spotykanej na największych stacjach w galaktyce, a tak rzadko na Pograniczu. Stanowi to miłą odmianę od wiecznej ciszy i pustki kosmosu, od której nie sposób uciec podczas długich podróży. A z takiej właśnie wróciłeś, dopiero przedwczoraj opuszcając załogę, z którą podpisałeś kontrakt jako ochroniarz. I choć zapłata pozwala ci zostać na stacji nadłużej, po dwóch dniach wracają ci chęci wylotu w kosmos. Zresztą, gdzie jest twój dom? Nie masz mieszkania ani nikogo bliskiego, nocując w hotelach lub na statkach, na pokładzie których przemierzasz gwiazdy. Idąc i tak rozmyślając, dostrzegasz hologram ogłaszający pobór najemników do armii jednej z frakcji Koalicji. Jako ochroniarz masz przeszkolenie wojskowe, a perspektywa sowitego wynagrodzenia i przerwania rutyny brzmi nadzwyczaj kusząco. Wiąże się to jednak ze sporym ryzykiem, a bardzo niechiałbyś pożegnać się ze swoim życiem w taki sposób. Z drugiej strony, w loży pilotów na pewno znajdzie się ktoś poszukujący dodatkowej pary rąk na pokładzie. A nuż trafi się ciekawa oferta? \nWybierz opcję: \nA - Centrum rekrutacyjne \nB - Loża pilotów",
          "armyCentre_3": "\"Raz się żyje\" myślisz wchodząc do centrum rekrutacyjnego. Zaraz po znalezieniu się w środku oślepia cię blask propagandowych hologramów, krzyczących o barbarzyckiej napaści na niewinną frakcję. Przy tylnej ścianie pomieszczenia znajduje się rząd biurek, za każdym siedzi pracownik ubrany w wojskowy mundur z gwiazdą - symbolen Kooperatywy Pulsara. Frakcja ta należ ydo Koalicji, jednak najwyraźniej w tym konflikcie postanowiła na własne wojska. A może nie miała wyboru? Z zamyślenia wyrywa cię komenda oficera, przywołującego cię do biurka. \n-Co oferujesz? - pyta prosto z mostu. \n\"Najwyraźniej bardzo potrzebują ludzi.\" - przemyka ci przez myśl. - Zajmuję się ochroną ludzi i zaopatrzenia. Mam przeszkolenie wojskowe oraz w pilotowaniu pojazdów bezzałogowych. A co wy oferujecie? - odpowiadasz \n-Pominę tu propagandę i powiem wprost - potrzeba nam żołnierzy do odbicia pewnej placówki naziemnej. Została ona zaatakowana z zaskoczeniai jeśli nie odbijemy jej w najbliższych dniach, wróg zdąży się przegrupować. Transportowiec odlatuje już za kilka godzin, nie będzie czasu na żadne dodatkowe przeszkolenie. Sprzęt i kombinezon otrzymasz na pokładzie, zapewniam jednak, że są najwyższej jakości. Stawka jest wysoka, jak i zapłata - 50 tysięcy kredytów. To jak, zgadzasz się? \nWybierz opcje: \nA - Zaakceptuj ofertę \nB - Targuj się o zapłatę \nC - Odrzuć ofertę",
          "warOfferAccepted_1": "-Zgadzam się - odpowiadasz. Wyraźnie zadowolony oficer gratuluje ci dokonania słusznego wyboru, po czym daje identyfikator i numer doku. \n-Prom odlatuje za 3 godziny. Zbierz swoje rzeczy i bądź na miejscu. Odmaszerować! Odwraczasz się i szybkim krokiem wracasz do hotelu. Po zebraniu swoich rzeczy i  wymeldowaniu się udajesz się w kierunku doku, z którego dolatuje prom. Obecny tam oficer sprawdza twoją przepustkę, a następnie prowadzi do mesy. Ledwie zdążysz przywitać się z innymi żołnierzami, a słyszysz dźwięk rozgrzewających się silników promu. Zanim się obejrzysz jednostka odrywa się od powierzchni i sprawnie wylatuje ze stacji. Chwilę później czujesz charakterystyczne wibracje wywołane przez napęd FSD, a gdy wyglądasz przez okno, widzisz gwiazdę systemu oddalonego o kilkadziesiąt lat świetlnych od miejsca, w którym przed chwilą wsiadałeś na pokład. \"A więc nie ma odwrotu\" myślisz, gdy prom ustawia kurs na docelowy posterunek. \nWybierz opcje: \nA - Kontynuuj",
          "warOfferRefused_1": "\"W taki sposób nie wygracie tej wojny\" - mówisz, wstając od stołu. Oficer poborowy krzyczy coś w twoją stronę, lecz ty go nie słuchasz. Sprawnym krokiem wychodzisz z budynku, po czym wtapiasz się w ruch uliczny. \"Może w loży znajdę mniej szaloną propozycję.\" - myślisz, krocząc szeroką aleją. \nWybierz opcje: \nA - Udaj się do loży pilotów",
          "warBargain_2": "\"Z pięśnią na ustach poszedłbym ginąć za waszą sprawę, lecz swoje życię cenię na więcej niż 50 tysięcy.\" - odpowiadasz oficerowi. \n-\"Zdajesz sobie sprawę, że nie jesteś nikim wyjątkowym?! 5o tysięcy za walkę po dobrej stronie to oferta nie do odrzucenia!\" - widać, że ten oficer nie lubi, kiedy się z nim dyskutuje. \n-\"Bardzo nisko cenicie ludzkie życie, oficerze.\" - odpowiadasz chłodno \n-\"Życie ludzkie nie znaczy nic gdy w grę wchodzi dobro Kooperatywy!\" - wykrzykuje wściekły wojskowy - \"50 tysięcy i ani kredyta więcej!\" \nWybierz opcje: \nA - Zaakceptuj ofertę \nB - Odrzuć ofertę",
          "warBriefing_2": "Po kilkunastu minutach lotu w systemie promem targnęło ostre szarpnięcie, po którym do życia obudziły się silniki manewrowe statku. Wyglądając przez okno, widzisz mały posterunek z widocznym z daleka hologramem giwazdy. Gdy prom zaczyna się do niego zbliżać, naprzeciw wam wylatują dwa małe myśliwce. Po dokłądnym przeskanowaniu dostajecie zgodę na lądowanie i prom ciężko osiada na płycie hangaru. Tuż zaraz po opuszczeniu pokładu wraz z innymi żołnierzami zostajesz skierowany do sali odpraw. Od razu rzuca ci się w oczy rygor i napięcie panujące w całych dokach, a także żołnierze w kombinezonach wojskowych stojący praktycznie na każdym rogu. Gdy wszyscy żołnierze z promu zajęli miejsca w sali, jak spod ziemi wyrósł wysoki i szczupły oficer z insygniami generała. /n-\"Nie mamy wiele czasu, więc przejdę do konkretów. 4 dni temu placówka naziemna Collins Market, która zgodnie z wolą mieszkańców należała do Kooperatywy Pulsara, została przejęta przez Rebelię Czarnego Skrzydła. Mimo, że wróg kontroluje całą placówkę, flocie Kooperatywy udało się nałożyć skuteczną blokadę. Do garnizonu powstańców wysłana została jednak karawana naziemna, której przybędzie do celu za 27 godzin. Do tego czasu placówka bezwzględnie musi zostać odbita, żeby uniknąć przedłużenia konfliktu i ograniczyć rozlew krwi. Po zakończeniu odprawy dostaniecie 9 godzin na sen i przygotowanie się, następnie pod eskortą myśliwców zsotaniecie wysłani do desantu na placówkę. Teraz zostaniecie podzieleni na role, szczegółowe plany zostaną wam przekazane przez oficerów. Jakieś pytania? Nie? W takim razie zapraszam do odpowiednich stanowisk. \" Jak na sygnał wszyscy obecni na sali wstali i zaczęli ustawiać się w odpowiednich kolejkach. Przed tobą rysują się dwie opcje - możesz wziąć udział w walce na planecie, jako szeregowy żołnierz, lub ubiegać się o fotel pilota myśliwca bezzałogowego, przeznaczonego do eskorty promów - dzięki długoletniemu ochranianiu konwojów masz w tym sporo doświadczenia. Ostatecznie decydujesz się na...  \nWybierz opcje: \nA - Ochranianie promów jako pilot bezzałogowca \nB - Dołączenie do walki jako żołnierz piechoty",
          "warLandingTroop_1": "Kolejka do stanowiska przesuwa się sprawnie i już po chwili trzymasz w ręku swoje rozkazy oraz identyfikator. Zanim jednak przygotujesz się do operacji, udajesz się do wspólnej sypialni i kładziesz się tam do snu, aby uspokoić organizm po podrózy. Na dźwięk budzika wstajesz i kierujesz się do zbrojowni. Stamtąd zabierasz przydzielony ci sprzęt, a następnie zmierzasz na strzelnicę. Tutaj kalibrujesz swój ekwipunek i kilkakrotnie trenujesz desanty planetarne w VR. Gdy z głośników słychać komunikat wzywający wszystkich żołnierzy na stanowiska, jesteś spokojny i przygotowany na wszystko. Łącznie z 40 innymi osobami zajmujecie miesjca na pokładzie opancerzonego transportera, który zrzuci was w pobliżu celu. Następnie wasza grupa ma za zadanie wedrzeć się do pomieszczenia generatora i odciąć zasilanie, co umożliwi innym grupom przedarcie się do centrum placówki. W czasie całej operacji zapewnione ma być wsparcie powietrzne, jednak jego zakres zależy od możliwości obrony przeciwlotniczej placówki. Gdy statek uruchamia silniki i obiera kurs w kierunku planety, czujesz zadziwiający spokój wewnętrzny. Jako że transportowiec ten ma opancerzony kadłub bez żadnych okien, nie masz wyboru jak ślepo zaufać dowodzącemu oficerowi. W miarę zbliżania się do powierzchni czujesz zwiększoną pracę silników. Nagle rozlega się huk i całym statkiem ostro szarpie. Praktycznie natychmiastowo odzywają się wieżyczki transportowca, jednak uderzenia stają się coraz częstsze. Nie masz czasu nad tym jednak myśleć, gdyż włąśnie w tym momencie otwierają się tylne wrota i oficer wydaje komendę do skoku. \nWybierz opcję: \nA - Kontynuuj",
          "warLanding_2": "Razem ze swoimi kompanami uruchamiasz swój kombinezon i wykonujesz skok. Podczas spadania widisz, jak na z placówki raz po raz wystrzeliwują lasery oraz pociski konwencjonalne. Niektóre działka obierają na cel twój oddział, jednak nieustanny ostrzał myśliwców Kooperatywy zmusza je do zmiany celu. Tuż nad powierzchnią aktywujesz silniki odrzutowe swojego kombinezonu i miękko na nogach lądujesz w pobliżu doków. Zaraz po dotknięciu ziemi dowódca wyznacza punkt zborny pomiędzy kontenerami zalegającymi w strefie magazynowej. Zaczynasz biec w tamtą stronę, starając się uniknąć ostrzału z budynków placówki. Zdajesz sobie jednak sprawę, że nie uda ci się dobiec do punktu na czas. Pozostają ci dwie możliwości: możesz spróbować oddać ogien, spowalniając bieg lecz dając twoim kompanom szansę na wyjście z przygwożdżenia ogniowego, lub ukryć się za pobliskim budynkiem i liczyć, że wrogowie zmienią cel. \nWybierz opcję: \nA - Oddaj ogień \nB - Schowaj się",
          "warHide_0": "Przerywasz bieg w kierunku kontenerów i ukrywasz się za pobliskim budynkiem. Wróg jednak dobrze widział twój ruch i teraz w twoją osłonę raz za razem uderzają pociski oraz promienie laserów. Nagle w pozycje powstańców uderza rakieta wystrzelona prawdopodobnie z jednego z eskorujących myśliwców. Wykorzystując moment, część twojego oddziału rozpoczyna natarcie pod ogniem zaporowym reszty żołnierzy. Im bliżej budynków przenoszą się walki, tym bardziej osamotniony zostajesz, podczas gdy żołnierze wroga zaczynają zdawać sobie sprawę, że jesteś sam. Już szykujesz się do próby przebicia się, gdy nagle słyszysz ostatni dźwięk w swoim życiu - stukot granata. W następnej sekundzie twoje ciało zostaje rozerwane na kawałki przez falę uderzeniową. \nKONIEC GRY",
          "warRun_2": "Nieznacznie zwalniając bieg, celujesz w stronę, skąd prowadzony jest ostrzał i naciskasz spust. Najpierw prowadzisz ogień krótkimi seriami, gdy jednak coraz więcej pocisków ląduje wokół ciebie przełączasz się na ogień automatyczny. W ostatnim momencie dobiegasz do kontenerów, jednak zastajesz tam cały twój oddział przgwożdżony ogniem zaporowym. Gdy wszystko wydaje się stracone, nagle słyszysz huk i nieprzyjacielski ogień na chwilę ustaje. Ta chwila starczy jednak, aby wychylić się zza osłony i otworzyć ogień, co też robi cały twój oddział. Teraz to powstańcy, w których pozycje trafiła rakieta prawdopodobnie wystrzelona z jednego z myśliwców Kooperatywy, znajdują się w gorszej sytuacji. Zauważa to również dowódca twojego oddziału, który wydaje komendę \"Naprzód!\". Rzucasz się do natarcia wraz z częścią oddziału, podczas gdy reszta zapewnia wam wsparcie ogniowe. Wasz atak przerywa gorączkowe próby przegrupowania powstańców, którzy zostają zlikwidowani bez większych trudności. Droga do generatora stoi przed wami otworem, trzeba jednak podjąć decyzję - która jest najlepsza? Większość oddziału jest za przedzieraniem sie przez wnętrza budynków, argumentując, że w ciasnych przestrzeniach łatwo przewyższymy przeciwnika siłą ognia. Część żołnierzy jest jednak za przedzieraniem się dachami i próbą uniknięcia otwartej konfrontacji. Ostatecznie dowódca wydaje rozkaz podzielenia oddziału na dwie grupy. Do której z nich dołączasz? \nWybierz opcje: \nA - Przedzieraj się wnętrzami budynków \nB - Przedzieraj się dachem",
          "warInside_0": "Razem z większością oddziału wysadzacie zewnętrzne drzwi i zalewacie ogniem pomieszczenie. W budynku nie ma ciśnienia, system podtrzymywania życia musiał zostać uszkodzony. Zachowując najwyższą gotowość ostrożnie wchodzicie do środka. Zostajecie przywitani nieprzyjacielskim ogniem, który jednak szybko ucicha po waszej dopowiedzi. Powoli, pomieszczenie po pomieszczeniu przesuwacie się w kierunku generatora, miażdżąc ogniem każdą napotkaną formę oporu. Gdy jednak wysadzacie kolejne drzwi, zamiast zabarykadowanego korytarza widzicie małego robota dostawczego z białą flagą. Zanim ktokolwiek z oddziału zorientuje się w sytuacji, robot z całą prędkością rusza w waszą stronę. Ostatnia rzecz, jaką w życiu widzisz to krzyk twojego kompana \"Kryć się!\". W następnej sekundzie ładunek termobaryczny ukryty w robocie eksploduje, kończąc życie całego oddziału. \nKONIEC GRY ",
          "warRoofs_1": "Wraz z garstką kompanów odłączacie się od głównego oddziału i wchodzicie na dach. Praktycznie z marszu jeden z was zostaje trafiony, a reszta nurkuje za znajdujące się tam urządzenia pomiarowe. Działając instynktownie, wyciągasz granat dymny i rzucasz go na otwartą przestrzeń. Na sygnał rzucacie się do biegu, przebiegacie przez mgłę i pędzicie wzdłuż wysokiej balustrady, zapewniającej wam minimalną osłonę. Następnie lawirujecie wśród różnego rodzaju szybów wentylacyjnych, aż dobiegacie do budynku reaktora. Podczas gdy jeden z was zakłąda ładunki na drzwi, nieskutecznie próbujesz nawiązać kontakt z drugą częścią oddziału. Po utworzeniu drogi do środka z zaskoczenia eliminujecie żołnierzy wroga i zabezpieczacie teren. Sprawnie odnajdujesz dźwignię awaryjnego wyłączenia i silnie ciągniesz ją w dół. Momentalnie gasną wszystkie światła w placówce, a zamki elektryczne w śluzach i grodziach tracą moc. Zadowolony z siebie, powiadamiasz dowództwo o pomyślnie wykonanym zadaniu. \nWybierz opcję: \nA - Kontynuuj",
          "warEnding_0": "Dzięki dobrze wykonanemu zadaniu szala zwycięstwa definitywnie przechyliła się na stronę Kooperatywy. Dzięki udanemu lądowaniu oraz odcięciu mocy w placówce, oddziały powstańców zostały rozbite przez skoordynowane odziały Kooperatywy przy wsparciu lotniczym. Przed kapitulacją ostatnich powstańców zdołali oni jednak wysłać sygnał do konwoju zmierzającego im na pomoc, przez co uniknął on rozbicia. Zwycięstwo Kooperatywy w konflikcie jest jednak zapewnione. Sama frakcja wywiązała się z umowy, dzięki czemu bilnas twojego konta zwiększył się o 50 tysięcy. Dzięki twojej nowej fortunie jetseś coraz bliżej zrealizowania swojego odwiecnzego marzenia posiadania własnego statku. Kosmos stoi przed tobą otworem... \nKONIEC GRY",
          "warFighterPilot_1": "Twoja decyzja o podjęciu roli pilota myśliwca wyraźnie zadowoliła oficera. Nie ma się co dziwić, znaczna większość osób, z którą rozmawiałeś to żołnierze wojsk lądowych, pewnie czujący się gdy mają grunt pod nogami. Po otrzymaniu swojego identyfikatora udałeś się do wspólnej sypialni, gdzie zażyłeś trochę snu na odnowienie sił. Następnie udałeś się do symulatora lotów, gdzie odświeżyłeś swoje umiejętności pilotażu, a gdy wybrzmiał komunikat wzywający wszystkich na stanowiska, udałeś się do swojego statku. Po krótkiej rozmowie z pilotami dostaliście zgodę na wylot. Gdy usiadłeś tylko usiadłeś w fotelu, ciężki kadłub transportowca uniósł się i poleciał w kierunku planety. \nWybierz opcje: \nA - Kontynuuj",
          "warFighterPilotEntrance_2": "Wyglądając przez wizjer, obserwujesz zbliżającą się powierzchnię planety. Podczas wejścia w atmosferę z zachwytem oglądałeś, jak płomienie smagają ciemny kadłub transportowca. Ten widok został jednak gwałtownie przerwany eksplozją, która wstrząsneła całym statkiem. \"Wieżyczki ognias! Wypuścić myśliwiec!\" wykrzyknął kapitan. W tym samym momencie, co twój monitor zabłysnął obrazem z myśliwca, wszystkie wieżyczki statku otworzyły ogień. Nie zwracasz jednak na to uwagi, skupiony na obrazie z monitora. Widać na nim dwa wrogie myśliwce załogowe, zbliżające się do twojego transportowca. Musisz szybko podjąć decyzję, od której mogą zależeć losy wszystkich ludzi na twoim statku. Możesz zdecydować się na bezpośrednie związanie ich walką, lub próbować je okrążyć i zmusić do rozbicia szyku. Jaka jest twoja decyzja? \nWybierz opcje: \nA - Walka bezpośrednia \nB - Rozbicie szyku",
          "warFighterPilotFight_2": "Przerzucając całą moc tarcz na przód, ruszasz prosto w nadlatujące myśliwce. Na pierwszy rzut oka wyglądają jak Viper mk4 i Eagle, małe i zwinne myśliwce z jednym pilotem. Każdy z nich ma znacznie większą siłę ognia od twojego bezzałogowego Taipana, jednak górujesz nad nimi zwinnością, a twoje małe rozmiany czyniaą cię trudnym celem. Twój manewr ewidentnie zaskoczył wrogich pilotów, gdyż przez długi czas strzelają w kierunku transportowca, dając ci wystarczająco dużo czasu na oddanie salwy we wrogiego Eagle-a. Gdy na monitorze pojawia się obraz rozdzieranego poszycia, nie możesz powstrzymać satydfakcji. Ranny Eagle gwałtownie skręca i zaczyna opadać. Chociaż nie został jeszce zniszczony, nie może już kontynuować ostrzału. W międzyczasie jednak Viper zdążył zmienić swój cel i teraz znajduje się za tobą. Jednocześnie coraz bardziej oddalasz się od swojego statku, który w każdej chwili może wymagać eskorty. \nWybierz opcje: \nA - Walcz z Viperem \nB - Wróć do statku",
          "warFighterPilotEscort_1": "Zmieniając tarcze na tył, zwiększasz maksymalnie moc silników i lecisz w kierunku swojego transportowca. Wrogi pilot wchodzi ci na ogon i zaczyna ostrzeliwywać. W dodatku transortowiec wszedł w zasięg naziemniej obrony przeciwlotniczej placówki, co mogło spowodować strącenie go w każdej chwili. Gdy już wszystko wydawało się stracone, dostrzegłeś na radarze symbol zbawienia - nadlatywały sojusznicze myśliwce. Ostatkiem sił swojego uszkodzonego bezzałogowca wykonałeś ostry zwrot, co zdezorientowało wroga na wystarczająco długo, by nowo przybyłe mysliwce otworzyły ogień. Pilot Vipera szybko stracił zainteresowanie swoimi niedoszłymi ofiarami, skupiając się na uratowaniu sobie życia. Nienękany już przez nikogo transportowiec sprawnie przeprowadził desant, po czym z rykiem silników oddalił się poza pole bitwy. Twoja misja została zakończona sukcesem. \nWybierz opcje: \nA - Kontynuuj",
          "warFighterPilotManeuver_2": "\"Walka bezpośrednia byłaby samobójstwem\" myślisz, zmieniając kurs myśliwca. Wrodzy piloci zdecydowali się skupić ogień na transportowcu, który to odpowiadał im ogniem z wieżyczek. Jasne jednak było, że w tym pojedynku będzie musiał jednak prędzej czy później ustąpić większemu liczebnie wrogowi. Czujesz , jak transportowiec przyjmuje cios za ciosem, coraz mocniej szarpiąc przy każdym uderzeniu. Skupiasz się jednak na obrazie monitora i celną serią przecinasz Vipera Mk4. Nie patrzysz na unoszący się dym z jego silników, lecz kierujesz ogień na jego kompana. Mimo że wrogi piot próbuje zmienić kurs, jest już dla niego za późno. Celną serią masakrujesz jego statek, który zaczyna płonąć i spada na ziemię. Słyszysz, jak z kabiny pilotów dobiega okrzyk radości, ty jednak nie masz czasu na świętowanie. Zauważyłeś w pobliżu grupę sojuszniczych myśliwców związanych walką z wrogami. Pokusa, aby im pomóc jes tbardzo duża, jednak otrzymałeś misję chronić transportowiec. \nWybierz opcje: \nA - Wróć do eskorty \nB - Dołącz do myśliwców",
          "warFighterPilotDogfight_0": "Instynktownie decydujesz się bronić przed oprawcą. Zwiększając moc silników, wykonujesz ostry zwrot i przelatujesz tuż pod wrogim ogniem. Przeciwnik jednak nie opduszcza i ponownie próbuje wziąć cię na cel. Ty jednak nie dajesz mu się i w wymianie ognia mocno uszkadzasz mu tarczę. Zdesperowany pilot podejmuje ostatnią próbę trafienia twojego zwinnego myśliwca, lecz ponownie to ty wychodzisz z manewru z przewagą, którą zaraz wykorzystujesz strącając go celną serią. Okrzyki radości zostają jednak gwałtownie przerwane mocniejszym niż wczesniej uderzeniem. To naziemna obrona przeciwlotnicza dostrzegła samotnie lecący transportowiec i obrała go na cel. Zdając sobie sprawę z powagi sytuacji, kierujesz się jak najszybciej z powrotem do statku. Nie jesteś jednak wystarczająco szybki. raz po raz trafiany transportowiec w końcu przegrywa walkę o przetrwanie i zaczyna niekontrolowanie spadać w dół. Zanim zdążysz wstać ze swojego stanowsika, zamienisz się w garść popiołu w płonącej kuli ognia, jaką stał się rozbity transportowiec. \nKONIEC GRY",
          "warFighterPilotJoin_0": "Chęć pomocy bierze nad tobą górę i kierujesz swój myśliwiec w kierunku pola bitwy. Piloci krzyczą do ciebie, abyś wracał, lecz ty ignorujesz ich rozkazy. Ledwie zdążysz jednak włączyć się do walki, a sojuszniczy miśliwiec zamienia w spadające szczątki statek kapitana powstańców. Strata ta powoduje popłoch w ich szeregach, dzięki czemu reszta jednostek bardzo szybko dołącza do grona wraków płonących na powierzchni. Mimo, że większośćstatków przeciwnika została pokonana, twój transportowiec pozostał bez ochrony. Zauważyła to też naziemna obrona przeciwlotnicza, skupiając na nim ogień. Zacząłeś wracać myśliwcem do transportowca, jednak było już za późno. Mimo heroicznych wysiłków pilotów, jeden z pocisków przebił pancerz w pobliżu silników, zamieniając transportowiec w kulę ognia i uśmiercając wszystkie osoby na pokładzie, łącznie z tobą. \nKONIEC GRY",
          "pilotLounge_2": "\"Wolę jednak żyć\" - myślisz, przechodząc obok centrum rekrutacjyjnego. O ile praca ochroniarza sama w sobie jest niebezpieczna, tak wstępywanie do armii to jednak zbyt duże ryzyko. Latanie w konwojach jest przyjemnym i z reguły spokojnym zadaniem, chyba że akurat trafią się piraci. I w dodatku płacą dobrze. Z zadumy wyrywa cię hałas, świadczący o bliskości loży pilotów. Jest to miesjce, w którym załogi statków zadokowanych na stacji mogą odpocząć przed lub po podróży i wymienić się informacjami z innymi pilotami. Można tam również bardzo często znaleźć wszelkiego rodzaju oferty pracy. Taki jest też twój cel, gdy wchodzisz do gwarnego baru. Od razu zagaduje cię pewien pilot stojący pod ścianą. \"Szukam ochrony. Muszę przewieźć trochę pewnej cennej substancji, lecz nie mogę sobie pozwolić na jej stratę. Wszystko musi zachowane w największej tajemnicy. Za dobre usługi pracę bardzo dobrze. Wchodisz?\" \nWybierz opcje: \nA - Zgadzam się \nB - Nie przemawia do mnie ta oferta",
          "pilotLoungeTrade_1": "\"Nie będę się angażował w ązdne nielegalne biznesy!\" odpowiadasz, odtrącając go. Niezadowolony przemytnik mruczy coś pod nosem i znika w głebi baru, podczas gdy ty zmierzasz w kierunku tarasu widokowego. Można z niego obserwować lądujące i startujące statki i tutaj też odbywa się większość rozmów w interesach. Podchodzisz do wiszącej na ścianie tablicy z aktualnościami. Oprócz najnowszych wiadomości z całej galaktyki piloci wywieszają na niej wszelakie oferty, w tym poszukiwania najemników. Dostrzegasz ogłoszenie pewnego handlarza potrzebującego strzelca do ochrony transportu platyny. Zachęcony dobrą płacą za na pozór łatwą pracę, postanawiasz skontaktować się z tym pilotem. \nWybierz opcje: \nA - kontynuuj",
          "pilotLoungeSmuggling_1": "\"Wchodzę w to\" - odpowiadasz. Nieznajomy kiwa głową i wsuwa ci w ręke mały wyświetlacz, a sam znika w cień. Na wyświetlaczu pokazany jest tylko adres i data. Zadowolony z możliwości zarobku kupujesz drinka w barze, a następnie wracasz do swojego hotelowego pokoju i zapadasz w sen. \nWybierz opcje: \nA - Kontynuuj",
          "pilotLoungeCaught_0": "Gdy nadzchodzi data podana na wyświetlaczu od nieznajomego, udajesz się pod adres na nim wskazany. Jest to jedno z masowo budowanych mieszkań w biedniejszych sektorach stacji, niczym nie wyróżniające się od innych. Gdy pukasz do drzwi, nieznajomy ogląda się czy nikogo z tobą nie ma i każe ci szybko wejść do środka. Przechodzicie z przedpokoju do salonu, gdzie nakazuje ci usiąść na starej kanapie i na niego poczekać. Po cwhili wraca z woreczkiem ususzonych liści. \n\"Wiesz co to jest?\" - pyta cię. Wiesz co to jest - onionhead, najpopularniejszy narkotyk w galaktyce. Legalny w niektórych systemach, w większości za posiadanie grozi więzienie lub śmierć. Nielegalny również tutaj. Na przemycie onionheadu można zarobić fortunę. \n-\"Wiem\" - odpowiadasz. \n-\"I wiesz ile można na tym zarobić. Mam ofertę kupna w sąsiednim systemie. Krótki kurs, a zarobić można nieźle. Zyskami dzielimy się 60-40. Stoi?\" \n-\"Stoi\" - odpowiadam. Nieznajomy kiwa głową usatysfakcjonowany i wychodzi z pomieszczenia. Ledwo zacząłeś myśleć o potencjalnych ryzykach i problemach, kiedy do pokoju wbiegają trzy osoby w kombinezonach i nieznajomy. \n-\"Stać policja!\" - wykrzykuje, podczas gdy policjanci rzucają cię na ziemię i skuwają kajdankami. - \"Jesteś aresztowany za udział w przemycie nielegalnych substancji.\" Zanim zdążysz cokolwiek powiedzieć, czujesz ukłucie w szyi i zapadasz w sen. \nKONIEC GRY",
          "pilotLoungeCruise_2": "Gdy pukasz do drzwi mieszkania wskazanego na adresie, otwiera je chuby, niski mężczyzna. Od razu poznajesz, że bardzo się cieszy z twojej obecności. Zaprasza cię do środka, a następnie częstuje kawą i herbatą. Przy herbatce ustalacie szczegóły zlecenia - za przewóz platyny do stacji docelowej oczymasz zapłatę 10 tysięcy kredytów. Ucieszony, że dobiłeś targu, wrcasz do hotelu i pakujesz swoje rzeczy, a następnie zapadasz w krótki sen. Po kilku godzinach wstajesz i udajesz się do hangaru, w którym stoi statek twojego pracodawcy - transportowiec Type - 9, ogromna maszyna zdolna przewozić wielkie ciężary. Z zadowoleniem zauważasz, że jak na statek transportowy jes tbardzo silnie uzbrojona. Po przywitaniu się z załogą i krótkiej odprawie ciężki statek odrywa się od płyty lądowiska i ustala kurs na stację docelową. Kiedy już się wydaje, że wszystko pójdzie jak z płatka, tuż przed celem podróży czujesz silny wstrząs, a nsatępnie uczucie spowalniania. \"To piraci! Wszyscy na stanowsika!\" krzyczy kapitan. Gdy siadasz na stanowisko strzelnicze i patrzysz na moniotry, widzisz dwa statki podążające w waszą stronę - jeden pękaty transportowiec i jeden mały myśliwiec. W takiej sytuacji od twoich rozkazów zależą losy załogi. \nWybierz opcje: \nA - Przygotować się do ucieczki! \nB - Przygotować się do obrony!",
          "pilotLoungeTragedy_0": "\"Silniki pełna moc!\" rozkazujesz, licząc na przegonienie agresorów. Jednak w czasie, kiedy napęd FSD się ładuje, zbliżyli się oni na odległość strzału, co też szybko robią. O ile pierwsza seria wystrzelona przez piratów była niecelna, tak druga znalazła swój cel - trafiony został prawy silnik. W takiej sytuacji nawet rozkazanie wyciągnięcia broni nie pomogło - seria po serii, piraci podziurawili twój statek aż zamienił się w dryfujące kawałki żelaza w kosmosie. \nKONIEC GRY",
          "pilotLoungeEnd_0": "\"Wysunąć działa!\" rozkazujesz, siadając w fotelu strzelca. W takich sytuacjach znajdowałeś się już nieraz i zdobyte doświadczenie na pewno ci teraz pomoże. Jak tylko działa są gotowe do strzału, posyłasz pierwszą serię w stronę agresora. Pirat musiał się tego nie spodziewać, ponieważ nawet nie zdążył zrobić uniku - seria przeszła przez środek jego statku, dziurawiąc kadłub w wielu miejscach. Wszelkie jego próby ratowania swojego życia były daremne - kolejne serie zakończyły żywot jego statlu, jak i jego samego. W takich okolicznościach drugi pirat podjął decyzję o odwrocie, uruchamiając napęd FSD i uciekając z pola bitwy. Jak tylko wieści o tym doszły załogi, cały statek wybuchnął oznakami radości, a sam właściciel obiecał ci podwyżkę. Jak się przekonałeś, nie kłamał, gdyż po doleceniu do celu i sfinalizowaniu transakcji bilans twojego konta zwiększył się o 15 tysięcy. I znowu jesteś na kolejnej stacji, bez domu, bez celu, bez pracy - jedyne co masz, to twoje oszczędności i pragnienie wolności. \nKONIEC GRY",
          "endEvent_0": "no i umarles"];
options["overview_4"] = ["A": "overviewEmpire_1", "B": "overviewFederation_1", "C": "overviewAlliance_1", "D": "introduction_2"];
options["overviewEmpire_1"] = ["A": "overview_4"];
options["overviewFederation_1"] = ["A": "overview_4"];
options["overviewAlliance_1"] = ["A": "overview_4"];
options["introduction_2"] = ["A": "armyCentre_3", "B": "pilotLounge_2"];
options["armyCentre_3"] = ["A": "warOfferAccepted_1", "B": "warBargain_2", "C": "warOfferRefused_1"];
options["warOfferRefused_1"] = ["A": "pilotLounge_2"];
options["warBargain_2"] = ["A": "warOfferAccepted_1", "B": "warOfferRefused_1"];
options["warOfferAccepted_1"] = ["A": "warBriefing_2"];
options["warBriefing_2"] = ["A": "warFighterPilot_1", "B": "warLandingTroop_1"];
options["warLandingTroop_1"] = ["A": "warLanding_2"]
options["warLanding_2"] = ["A": "warRun_2", "B": "warHide_0"];
options["warRun_2"] = ["A": "warInside_0", "B": "warRoofs_1"];
options["warRoofs_1"] = ["A": "warEnding_0"];
options["warFighterPilot_1"] = ["A": "warFighterPilotEntrance_2"];
options["warFighterPilotEntrance_2"] = ["A": "warFighterPilotFight_2", "B": "warFighterPilotManeuver_2"];
options["warFighterPilotManeuver_2"] = ["A": "warFighterPilotEscort_1", "B": "warFighterPilotJoin_0"]
options["warFighterPilotFight_2"] = ["A": "warFighterPilotDogfight_0", "B": "warFighterPilotEscort_1"];
options["warFighterPilotEscort_1"] = ["A": "warEnding_0"];
options["pilotLounge_2"] = ["A": "pilotLoungeSmuggling_1", "B": "pilotLoungeTrade_1"];
options["pilotLoungeSmuggling_1"] = ["A": "pilotLoungeCaught_0"];
options["pilotLoungeTrade_1"] = ["A": "pilotLoungeCruise_2"];
options["pilotLoungeCruise_2"] = ["A": "pilotLoungeTragedy_0", "B": "pilotLoungeEnd_0"];
var eventName = "overview_4";
var eventText = "Jest rok 3308 i ludzkość panuje nad kosmosem. Dzięki wynalezieniu napędu FSD, paliwa wodorowego i kompputerów potężniejszych, niż kiedykolwiek wcześniej, gwiazdy znalazły się w zasięgu ręki. Poczynając od 22 wieku, ludzkość masowo zaczyna kolonizwoać kosmos. Jednak o ile na Ziemi wojna światowa dobitnie pokazała, że jedynie zjednoczona ludzkość przeżyje, odkrywcy kosmosu zapomnieli o tej lekcji. Już pierwsza ludzka kolonia poza Układem Słonecznym wkrótce po osiągnięciu samowystarczalności ogłosiła niepodległość, zmuszając władze z Ziemi do zbrojnej interwencji. I o ile obie strony doszły w końcu do ugody, tak nie zakończyło to sporów na zawsze. Ludzka chciwość doprowadziła do wytępienia wszystkich obcych form życia, najpierw na Tau Ceti, a potem w kolejnych koloniach. I o ile z czasem ludzie zaczęli przykładać większą wagę do ochrony obcych, tak cały czas nie mogą pogodzić się ze sobą. Na tym polega paradoks ludzkiego zachowania: mimo, że praktycznie nieskończony wszechświat jest na wyciągnięcie ręki, ludzie i tak walczą między sobą o najmniejszą drobnostkę, przelewając niepotrzebnie krew. Dzisiaj, kiedy zasiedlonych systemów są tysiące, a populację ludzkości liczy się w tryliardach, trzy największe mocarstwa rywalizują o wpływy w zamieszkałej przestrzeni: Imperium, Federacja i Sojusz. Mimo ich nieustannych nacisków tysiące systemów wybierają \"czwartą drogę\", będąc niezależnymi od żadnego z nich. Wybierz opcję: \nA - Informacje o Imperium \nB - informacje o Federacji \nC - informacje o Sojuszu \nD - kontynuuj fabułę";
var choice = "";
print(eventText);
while(game){
    var optionCounter = 0;
    var isValidOption = false;
    let amountOfOptionsIndex = eventName.index(eventName.endIndex, offsetBy: -1);
    let amountOfOptions = eventName[amountOfOptionsIndex...];
    let tempOptions = Int(amountOfOptions) ?? 0;
    if(tempOptions != 0){
        choice = readLine() ?? "";
    }
    if(tempOptions == 0){
        game = false;
    }
    for i in alphabet{
        if(String(i) == choice && optionCounter < tempOptions){
            isValidOption = true;
            break;
        }
        optionCounter += 1;
    }
    if(isValidOption){
        eventText = events[options[eventName]![choice]!]!;
        eventName = options[eventName]![choice]!;
        print(eventText);
    }else{
        if(tempOptions == 0){
            continue;
        }else{
            print("Nie ma takiej opcji");
        }
    }
}

